API_KEY: null
HPC:
  hostname: null
  localdir: /nfshome/villa/pynter-data
  workdir: null
dbconfig:
  vasp:
    collection: vasp
    database: pynter
    host: 127.0.0.1
    password: null
    port: 27017
    user: null
job_settings:
  sbatch_kwargs:
    account: ''
    error: err.%j
    mail-user: null
    mem-per-cpu: 3500
    ntasks: null
    job-name: no_name
    output: out.%j
    partition: null
    processor: null
    time: 01:00:00
  add_automation: null
  add_lines_body: null
  add_lines_header: null
  add_stop_array: false
  array_size: null
  filename: job.sh
  modules: null
  path_exe: ''
