HPC:
  hostname: 
  localdir: 
  workdir: 

API_KEY: 

job_settings:
    project_id:
    name: no_name
    array_size: 
    email: 
    nodes: 4
    cores_per_node: 24
    output_filename: out.%j
    error_filename: err.%j
    timelimit: '24:00:00'
    memory_per_cpu: 2400
    processor: avx2
    modules:
    - intel/2019.2
    - intel/2019.3
    - intelmpi/2019.3
    - fftw/3.3.8
    path_exe: 
    add_stop_array: true
    add_automation: 
    add_lines_header: 
    add_lines_body: 
    filename: job.sh

dbconfig:
  vasp:
    collection: test-matgendb
    database: vasp
    host: 127.0.0.1
    password: null
    port: 27017
    user: null
